### ISSUE TITLE
Unable to install on Laravel 8

### ISSUE THREAD

**Issue by iAcki** [radicalloop/eodhistoricaldata#10]
Hi,

I'm getting a composer error while trying to install it on a Laravel 8 project. I assume it depends on the support version:

> Problem 1
>     - radicalloop/eodhistoricaldata[3.0.0, ..., 3.0.1] require illuminate/support ^7.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.74).
>     - Root composer.json requires radicalloop/eodhistoricaldata ^3.0 -> satisfiable by radicalloop/eodhistoricaldata[3.0.0, 3.0.1].

I'm using version 8.74 of "illuminate/support".

"illuminate/support": "^8.74",

Thanks, Christian

**Comment by jimitit** [comment]
Thanks @iAcki  for reporting. 

We've fixed it. Please check now.
