### ISSUE TITLE
Get Exchange details

### ISSUE THREAD

**Issue by Degn** [radicalloop/eodhistoricaldata#5]
Hello, 

I **love** this wrapper but it seems like the development has stopped a few years back and I would really like if you could add new EOD endpoints such as https://eodhistoricaldata.com/financial-apis/exchanges-api-trading-hours-and-holidays/ to your wrapper! 

I hope you like the idea :-) 

Simon

**Comment by jimitit** [comment]
Definitely, we'll add new endpoints soon. Thanks Simon.

**Comment by radicalloop** [comment]
Okay, @Degn. Mentioned endpoint is handled. 

Thanks
