### ISSUE TITLE
Guzzle version issue 

### ISSUE THREAD

**Issue by m-rizwan-ashlar** [radicalloop/eodhistoricaldata#9]
in laravel 8 guzzle version is 7+. thats why its not working in laravel 8.

Problem 1
    - Root composer.json requires radicalloop/eodhistoricaldata ~2.0 -> satisfiable by radicalloop/eodhistoricaldata[2.0.0].
    - radicalloop/eodhistoricaldata 2.0.0 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

if we downgrade guzzle version to 6.3 
Problem 1
    - Root composer.json requires radicalloop/eodhistoricaldata ~2.0 -> satisfiable by radicalloop/eodhistoricaldata[2.0.0].
    - Conclusion: don't install laravel/framework v8.55.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.56.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.57.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.58.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.59.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.60.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.61.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.54.0 (conflict analysis result)
    - radicalloop/eodhistoricaldata 2.0.0 requires illuminate/support ^6.0 -> satisfiable by illuminate/support[v6.0.0, ..., 6.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v1.0.0, v1.1.0, v1.1.1, v1.1.2, v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.54.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^8.54 -> satisfiable by laravel/framework[v8.54.0, ..., 8.x-dev].

**Comment by ReDraft** [comment]
Same Problem, how can we fix this? Anyone find a Solution for this?

**Comment by jimitit** [comment]
@ReDraft  Fixed it.  Please check now.
